version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: omniauth
    versions:
    - "> 1.9.1"
  - dependency-name: omniauth-auth0
    versions:
    - "> 2.6.0"
  - dependency-name: omniauth-rails_csrf_protection
    versions:
    - 1.0.0
  - dependency-name: puma
    versions:
    - 5.2.2
  - dependency-name: rails
    versions:
    - 6.1.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack-cli
    versions:
    - ">= 4.a, < 5"
  - dependency-name: jquery
    versions:
    - 3.6.0
  - dependency-name: "@rails/activestorage"
    versions:
    - 6.1.3
  - dependency-name: "@rails/actioncable"
    versions:
    - 6.1.3
